name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VALGRIND: "--leak-check=full --track-origins=yes"
  
jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: pobedos/myapp:1.1

    steps:        
    - uses: actions/checkout@v2
    
    - name: build
      run: make build
    - name: run
      run: make run
  
  test:
  
    needs: build
    runs-on: ubuntu-latest
    container:
      image: pobedos/myapp:1.1
    
    steps:
    - uses: actions/checkout@v2
      
    - name: unit
      run: ./test.sh
