name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: pobedos/myapp:1.3

    steps:        
    - uses: actions/checkout@v2
    
    - name: build
      run: make build
    - name: run
      run: make run
  
  unit:
  
    needs: build
    runs-on: ubuntu-latest
    container:
      image: pobedos/myapp:1.3
    
    steps:
    - uses: actions/checkout@v2
      
    - name: unit
      run: make test
      
  test:
  
    needs: build
    runs-on: ubuntu-latest
    container:
      image: pobedos/myapp:1.2
    
    steps:
    - uses: actions/checkout@v2
      
    - name: test
      run: /test/test.sh
